apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.nameSpace}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-name" $ }}-deployment
  namespace: {{ $.Values.nameSpace }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-pod-selector-labels" $ | nindent 6 }}
  template:
    spec:
      containers:
        - name: {{ include "chart-name" $ }}
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          ports:
            {{- include "web-container-ports" $ | nindent 12 }}
          {{- include "web-container-resources" $ | nindent 10 }}
    metadata:
      labels:
        {{- include "web-pod-selector-labels" $ | nindent 8 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-name" $ }}-service
  namespace: {{ $.Values.nameSpace }}
  {{- if $.Values.service.annotations }}
  annotations: 
    {{- toYaml $.Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    {{- include "service-ports" $ | nindent 4 }}
  selector:
    {{- include "web-pod-selector-labels" $ | nindent 4 }}

---

{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ $.Values.nameSpace }}
  name: {{ include "chart-name" $ }}-ingress
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: mypictures.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ include "chart-name" $ }}-service
              servicePort: 80
{{- end }}

        


