apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nginx-kluster
  region: us-east-2


fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system

  - name: fp-nginx
    selectors: 
      - namespace: nginx-ns
