# Default values for pictures-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameSpace: nginx-ns
replicaCount: 1

image:
  repository: 224925781520.dkr.ecr.us-east-2.amazonaws.com/vlab2
  tag: nginx-blue
  ports: 
    - name: http
      containerPort: 80
      protocol: tcp

service:
  type: NodePort
  ports: 
    - name: web-port
      port: 80
      targetPort: 80
      nodePort: 30010

resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

ingress:
  enabled: false
  

